name = "attention-reclaim"
compatibility_date = "2026-09-06"
workers_dev = true
preview_urls = true

[assets]
directory = "./"
not_found_handling = "404-page"

[[routes]]
pattern = "mindreclaim.org"
custom_domain = true
